### ISSUE TITLE
plz helpppp

### ISSUE THREAD

**Issue by Gpsdwe** [Michal2SAB/Ethereum-Stealer#18]
![image](https://github.com/Michal2SAB/Ethereum-Stealer/assets/141666584/87ada1a1-b5eb-4238-85d0-3db744a1ad7b)

**Comment by leb-ben** [comment]
so I mean this is 1 way of doing it, however if anyone wants I have a much more efficient way of instead of generating private keys from random 12 word seed phrases, since like, pretty should if it was running a billion checks concurrently per milla seconds it would still take billions of years to even check a noteworthy amount of possible keys lol.  

Without giving it all away, I already have scripts written in python and node that can... well lets says more efficiently obtain addresses to scan and their prive keys, , aka not relying on random generations at any point, in relations to the context here anyhow, plus it is concurrently checking every address against 104 chains, and everything possible on those chains, including nfts and smart contracts / lp tokens, stakings, all that.  Now, this is considering it is doing all those things, and very cleaning printing out any addresses found, LIVE, with positive balances, and in nice colors with added lines for directly relivant info, like the chains, and things you would otherwise be manually checking urself, like actively updated filters to not bog shit down with scam token findings, or honey pots, etc.. All that considered, it is returning and performing all the previous plus more on average 5 addresses that at least already EXISTED. Additionally the scripts have many presets options for narrowing or broadening what and how u want to be doing this, even how u wants it displayed, and just cuz im awesome, it immediately writes addresses with a positive balance of any amount to a local json PLUS has safies set to be outputting those as well if the script terminates for any reason so that a long scan wouldn't ever end up in u missing something, and this also allowing for easily picking up where left of in the worst case unexpected problems. Please DM me if you are interested, I'm willing to rent it out for runs without the code super cheap, sell any of the individual scripts, or even give free privalleges access to anyone that can provide me with code / scripts that could benefit being added to the currently project. (*note the project is obviously not publicly listed anywhere. ) Please also note, I'm not about taking from the poor neither, the projects goal is actually much greater then that. so not black hat, but probably considered gray for obvious reasons. if your 100% black hat, telling u now don't waste ur time, were not going to be able to negotiate, however if u can provide evidence of atleast gray hat I'd probably work with you.

**Comment by maxxxxing** [comment]
> so I mean this is 1 way of doing it, however if anyone wants I have a much more efficient way of instead of generating private keys from random 12 word seed phrases, since like, pretty should if it was running a billion checks concurrently per milla seconds it would still take billions of years to even check a noteworthy amount of possible keys lol.
> 
> Without giving it all away, I already have scripts written in python and node that can... well lets says more efficiently obtain addresses to scan and their prive keys, , aka not relying on random generations at any point, in relations to the context here anyhow, plus it is concurrently checking every address against 104 chains, and everything possible on those chains, including nfts and smart contracts / lp tokens, stakings, all that. Now, this is considering it is doing all those things, and very cleaning printing out any addresses found, LIVE, with positive balances, and in nice colors with added lines for directly relivant info, like the chains, and things you would otherwise be manually checking urself, like actively updated filters to not bog shit down with scam token findings, or honey pots, etc.. All that considered, it is returning and performing all the previous plus more on average 5 addresses that at least already EXISTED. Additionally the scripts have many presets options for narrowing or broadening what and how u want to be doing this, even how u wants it displayed, and just cuz im awesome, it immediately writes addresses with a positive balance of any amount to a local json PLUS has safies set to be outputting those as well if the script terminates for any reason so that a long scan wouldn't ever end up in u missing something, and this also allowing for easily picking up where left of in the worst case unexpected problems. Please DM me if you are interested, I'm willing to rent it out for runs without the code super cheap, sell any of the individual scripts, or even give free privalleges access to anyone that can provide me with code / scripts that could benefit being added to the currently project. (*note the project is obviously not publicly listed anywhere. ) Please also note, I'm not about taking from the poor neither, the projects goal is actually much greater then that. so not black hat, but probably considered gray for obvious reasons. if your 100% black hat, telling u now don't waste ur time, were not going to be able to negotiate, however if u can provide evidence of atleast gray hat I'd probably work with you.

i have programs that i can give you email me at atypicalglue@gmail.com

**Comment by Michal2SAB** [comment]
Either outdated code for the version of the module or you didn't install any
